# lv4. 우유와 요거트가 담긴 장바구니
SELECT DISTINCT a.CART_ID
FROM CART_PRODUCTS a
WHERE a.CART_ID IN (SELECT b.CART_ID FROM CART_PRODUCTS b WHERE b.NAME = 'Milk')
AND a.CART_ID IN (SELECT c.CART_ID FROM CART_PRODUCTS c WHERE c.NAME = 'Yogurt');
